Release of GeoNetwork 4.2.0.
geonetwork/docker-geonetwork pull request #85
Opened 2022-05-20 10:37 UTC by fxprunayre

2022-05-20 10:59 UTC, juanluisrp commented
@fxprunayre can you add a warning in https://github.com/docker-library/docs/blob/master/geonetwork/content.md, for example at the start of the _How to use this image_ section about the 4.2.0 and the H2 update procedure?

2022-05-20 11:15 UTC, juanluisrp requested changes

2022-05-20 11:15 UTC, juanluisrp commented on 4.2.0/Dockerfile
> +ENV GN_DOWNLOAD_MD5 3351b899162b9260459c6c76d1d8f446
I'm getting this error when trying to build the image from `4.2.0`:

```
md5sum: WARNING: 1 computed checksum did NOT match.
```

MD5 defined in the Dockerfile is not valid. ` GN_DOWNLOAD_MD5` is set to `3351b899162b9260459c6c76d1d8f446` but it should be `5300f81f24f1585d969e667d922e8e8e`.

2022-05-20 11:17 UTC, juanluisrp commented on 4.2.0/Dockerfile
> +ENV GN_DOWNLOAD_MD5 3351b899162b9260459c6c76d1d8f446
Updated.

2022-05-20 11:22 UTC, juanluisrp approved these changes

2022-05-20 11:27 UTC, merged

2022-05-23 08:31 UTC, fxprunayre commented
Thanks @juanluisrp